In [111]:
from sympy import *

In [131]:
x0 = symbols("x0", commutative=False)
x1 = symbols("x1", commutative=False)
x2 = symbols("x2", commutative=False)

y0 = symbols("y0", commutative=False)
y1 = symbols("y1", commutative=False)
y2 = symbols("y2", commutative=False)

z0 = symbols("z0", commutative=False)
z1 = symbols("z1", commutative=False)
z2 = symbols("z2", commutative=False)

I0 = symbols("I0")
I1 = symbols("I1")
I2 = symbols("I2")

In [132]:
a0=1/2*(x0+1j*y0)
a1=1/2*(x1+1j*y1)
a2=1/2*(x2+1j*y2)

ad0=1/2*(x0-1j*y0)
ad1=1/2*(x1-1j*y1)
ad2=1/2*(x2-1j*y2)

In [133]:
A=simplify((a0+ ad0)*I1*I2)
A

I1*I2*x0

In [134]:
expand(ad0*a0)

0.25*I*x0*y0 + 0.25*x0**2 - 0.25*I*y0*x0 + 0.25*y0**2

In [128]:
B=simplify(a1*ad2 + ad1*a2)
B

0.5*(x1*x2 + y1*y2)

In [108]:
B=simplify(I0*(a1*ad2 + ad1*a2))
B

0.5*I0*(x1*x2 + y1*y2)

In [125]:
C=simplify(a0*a1*ad2 + ad0*ad1*a2)
C

0.25*(x0*x1*x2 + x0*y1*y2 + y0*x1*y2 - y0*y1*x2)

In [36]:
A+B+C

0.5*I0*(x1*x2 + y1*y2) + 1.0*I1*I2*x0 + 0.25*x0*x1*x2 + 0.25*x0*y1*y2 + 0.25*x1*y0*y2 - 0.25*x2*y0*y1

In [37]:
# 4*simplify(a2*a1*ad0 + ad2*ad1*a0)

In [8]:
import numpy as np

In [58]:
I = np.array([[1, 0],
              [0, 1]])
X = np.array([[0, 1],
              [1, 0]])
Y = np.array([[0, -1j],
              [1j, 0]])
Z = np.array([[1, 0],
              [0, -1]])

In [42]:
AA=1/4*(np.kron(X,np.kron(X,X))+np.kron(X,np.kron(Y,Y))+np.kron(Y,np.kron(X,Y))-np.kron(Y,np.kron(Y,X)))

In [43]:
np.real(AA), np.max(np.imag(AA))

(array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 0.0)

In [65]:
zero=np.array([[1],[0]])
one=np.array([[0],[1]])
plus=np.array([[1],[1]])/np.sqrt(2)
minus=np.array([[1],[-1]])/np.sqrt(2)

In [13]:
zzo = np.kron(zero,np.kron(zero,one))
ooz = np.kron(one,np.kron(one,zero))
ozo = np.kron(one,np.kron(zero,one))

In [90]:
H=(np.kron(X,X)+np.kron(Y,Y))/2
v=np.kron(one,zero)+np.kron(zero,one)

print(H.dot(v),v)

le,ve = np.linalg.eig(H)
for i in range(2**2):
    print(H@ve[:,i]-le[i]*ve[:,i])
print("eigenvectors")
for i in range(2**2):
    print(np.real(ve[:,i]))

[[0.+0.j]
 [1.+0.j]
 [1.+0.j]
 [0.+0.j]] [[0]
 [1]
 [1]
 [0]]
[0.00000000e+00+0.j 1.11022302e-16+0.j 5.55111512e-16+0.j
 0.00000000e+00+0.j]
[ 0.00000000e+00+0.j -1.11022302e-16+0.j  1.11022302e-16+0.j
  0.00000000e+00+0.j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
eigenvectors
[-0.          0.70710678  0.70710678 -0.        ]
[ 0.          0.70710678 -0.70710678  0.        ]
[1. 0. 0. 0.]
[0. 0. 0. 1.]


In [91]:
np.kron(one, one)

array([[0],
       [0],
       [0],
       [1]])

In [14]:
np.max(np.real(A.dot(zzo)-ooz)), np.max(np.imag(A.dot(zzo)-ooz))

(0.0, 0.0)

In [15]:
np.max(np.real(A.dot(ooz)-zzo)), np.max(np.imag(A.dot(ooz)-zzo))

(0.0, 0.0)

In [16]:
ooz, zzo, ozo

(array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0]]),
 array([[0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0]]))

In [18]:
# 001 -> 110 -> 101 -> 001

In [143]:
(.5*(X+1j*Y))@zero, (.5*(X+1j*Y))@one

(array([[0.+0.j],
        [0.+0.j]]),
 array([[1.+0.j],
        [0.+0.j]]))

In [144]:
(.5*(X-1j*Y))@zero, (.5*(X-1j*Y))@one

(array([[0.+0.j],
        [1.+0.j]]),
 array([[0.+0.j],
        [0.+0.j]]))

In [146]:
(.5*(X-1j*Y))@(.5*(X+1j*Y))@zero, (.5*(X-1j*Y))@(.5*(X+1j*Y))@one

(array([[0.+0.j],
        [0.+0.j]]),
 array([[0.+0.j],
        [1.+0.j]]))

In [147]:
(.5*(X+1j*Y))@(.5*(X-1j*Y))@zero, (.5*(X+1j*Y))@(.5*(X-1j*Y))@one

(array([[1.+0.j],
        [0.+0.j]]),
 array([[0.+0.j],
        [0.+0.j]]))

In [99]:
A=1/4*(np.kron(X,np.kron(X,X))+np.kron(X,np.kron(Y,Y))+np.kron(Y,np.kron(X,Y))-np.kron(Y,np.kron(Y,X)))
B=1/2*(np.kron(I,np.kron(X,X))+np.kron(I,np.kron(Y,Y)))
C=np.kron(I,np.kron(I,X))

In [105]:
A@np.kron(one,np.kron(zero,one)),\
B@np.kron(one,np.kron(zero,one)),\
C@np.kron(one,np.kron(zero,one))

(array([[0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j]]),
 array([[0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [1.+0.j],
        [0.+0.j]]),
 array([[0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0]]))

In [104]:
A@np.kron(one,np.kron(one,zero))-np.kron(zero,np.kron(zero,one)),\
B@np.kron(one,np.kron(one,zero)),\
C@np.kron(one,np.kron(one,zero))

(array([[0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j]]),
 array([[0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [1.+0.j],
        [0.+0.j],
        [0.+0.j]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1]]))