In [2]:
# import sys
# sys.path.append('../')

# from qiskit_utilities.mixers import *
from mixers import *
import math

In [3]:
from IPython.display import display
np.set_printoptions(suppress=True)

In [4]:
def scost(l,n):
    if n<2 or l>n:
        return 0
    if n==2:
        if l==2:
            return l
        else:
            return 0
    else:
        return scost(l,n-1)+scost(l-1,n-1)
ls=''
for n in range(2,16):
    cost=0
    for l in range(2,n+1):
        cost+=2*(l-1)*scost(l,n)
    ls+="& "+str(cost)
    print("cost(",n,")=",cost)
print(ls)

# ls=''
# for n in range(2,16):
#     cost=0
#     for l in range(2,n+1):
#         cost+=2*(l-1)*math.comb(l,n)
#     ls+="& "+str(cost)
#     print("cost(",n,")=",cost)
# print(ls)

cost( 2 )= 4
cost( 3 )= 12
cost( 4 )= 32
cost( 5 )= 80
cost( 6 )= 192
cost( 7 )= 448
cost( 8 )= 1024
cost( 9 )= 2304
cost( 10 )= 5120
cost( 11 )= 11264
cost( 12 )= 24576
cost( 13 )= 53248
cost( 14 )= 114688
cost( 15 )= 245760
& 4& 12& 32& 80& 192& 448& 1024& 2304& 5120& 11264& 24576& 53248& 114688& 245760


In [5]:
for n in range(2,16):
    print((n**2-n)/2)

1.0
3.0
6.0
10.0
15.0
21.0
28.0
36.0
45.0
55.0
66.0
78.0
91.0
105.0


In [6]:
# for n in range(2,6):
#     row=[]
#     for l in range(2,n+1):
#         row.append(scost(l,n))
#     display(row)
# for n in range(2,6):
#     row=[]
#     for l in range(2,n+1):
#         row.append(math.comb(n,l))
#     display(row)

In [6]:
# #populate counts
# for n  in range(2,10):
#     nums=np.zeros((n,n))
#     for i in range(n):
#         for j in range(n):
#             nums[j,i] = scost(i+1,j+1)
#     weights=np.zeros(n)
#     for i in range(n):
#         weights[i]=2*(i+1)
# #     display(nums)
# #     display(weights)
# #     display(nums.dot(weights))
#     display(nums[-1,:],weights)
#     display(np.sum(np.dot(nums[-1,:],weights)))

In [4]:
s=0
for n in range(1,8):
    T1=get_T(2**n,mode='standard',d=1)
    for k in range(1,10):
        Tkm1=get_T(2**n,mode='standard',d=k-1)
        Tk=get_T(2**n,mode='standard',d=k)
        Tkp1=get_T(2**n,mode='standard',d=k+1)
        s+=np.max(np.matmul(Tk,T1)-((n-(k-1))*Tkm1+(k+1)*Tkp1))
display(s)

0.0

In [5]:
n=4
T={}
T[1]=get_T(n,mode='nearest_int',d=1)
for k in range(2,5):
    T[k]=np.matmul(T[k-1],T[1])
display(T)

T={}
T[1]=get_T(n,mode='nearest_int_cyclic',d=1)
for k in range(2,5):
    T[k]=np.matmul(T[k-1],T[1])
display(T)
### for n in range(1,10):
#     T1=get_T(2**n,mode='standard',d=1)
#     for k in range(1,10):
#         Tkm1=get_T(2**n,mode='standard',d=k-1)
#         Tk=get_T(2**n,mode='standard',d=k)
#         Tkp1=get_T(2**n,mode='standard',d=k+1)
#         display(np.max(np.matmul(Tk,T1)-((n-(k-1))*Tkm1+(k+1)*Tkp1)))

{1: array([[0., 1., 0., 0.],
        [1., 0., 1., 0.],
        [0., 1., 0., 1.],
        [0., 0., 1., 0.]]),
 2: array([[1., 0., 1., 0.],
        [0., 2., 0., 1.],
        [1., 0., 2., 0.],
        [0., 1., 0., 1.]]),
 3: array([[0., 2., 0., 1.],
        [2., 0., 3., 0.],
        [0., 3., 0., 2.],
        [1., 0., 2., 0.]]),
 4: array([[2., 0., 3., 0.],
        [0., 5., 0., 3.],
        [3., 0., 5., 0.],
        [0., 3., 0., 2.]])}

{1: array([[0., 1., 0., 1.],
        [1., 0., 1., 0.],
        [0., 1., 0., 1.],
        [1., 0., 1., 0.]]),
 2: array([[2., 0., 2., 0.],
        [0., 2., 0., 2.],
        [2., 0., 2., 0.],
        [0., 2., 0., 2.]]),
 3: array([[0., 4., 0., 4.],
        [4., 0., 4., 0.],
        [0., 4., 0., 4.],
        [4., 0., 4., 0.]]),
 4: array([[8., 0., 8., 0.],
        [0., 8., 0., 8.],
        [8., 0., 8., 0.],
        [0., 8., 0., 8.]])}

In [9]:
get_T(2**4,mode='standard',d=1)

array([[0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,

In [10]:
for n in range(2,10):
    print(np.linalg.norm(np.ones(2**n),2)-2**(n/2))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [11]:
tmp=['100','010','001']
tmp_neg=get_bitwise_negated_strings(tmp)
tmp, tmp_neg, get_overlap(tmp,tmp_neg), get_minus(tmp_neg,tmp)

(['100', '010', '001'],
 ['011', '101', '110'],
 [],
 (['011', '101', '110'], [0, 1, 2]))

In [12]:
tmp=['001','111','101']
tmp_neg=get_bitwise_negated_strings(tmp)
tmp, tmp_neg, get_overlap(tmp,tmp_neg), get_minus(tmp_neg,tmp)

(['001', '111', '101'],
 ['110', '000', '010'],
 [],
 (['110', '000', '010'], [0, 1, 2]))

In [13]:
tmp=['100','010','011']
tmp_neg=get_bitwise_negated_strings(tmp)
tmp, tmp_neg, get_overlap(tmp,tmp_neg), get_minus(tmp_neg,tmp)

(['100', '010', '011'], ['011', '101', '100'], ['100', '011'], (['101'], [1]))

In [14]:
tmp=['100','010','001','011']
tmp_neg=get_bitwise_negated_strings(tmp)
minus, m_ind = get_minus(tmp_neg,tmp)
tmp, tmp_neg, get_overlap(tmp,tmp_neg), minus, m_ind

(['100', '010', '001', '011'],
 ['011', '101', '110', '100'],
 ['100', '011'],
 ['101', '110'],
 [1, 2])

In [15]:
# for mask in all_states(3):
#     display(get_negated_strings(tmp,mask))

In [16]:
# T[m_ind].T[m_ind].T

In [17]:

H=get_H(['0100','1000','0010','0001'],get_T(4,"nearest_int"),simplify=False)
H+=get_H(['0101','1001'],get_T(2,"nearest_int"),simplify=False)
H+=get_H(['0110','1010'],get_T(2,"nearest_int"),simplify=False)
H+=get_H(['0111','1011'],get_T(2,"nearest_int"),simplify=False)

H=simplifyH(H)
display(H)

#sqg, #cnots= (0, 36)
#sqg, #cnots= (0, 12)
#sqg, #cnots= (0, 12)
#sqg, #cnots= (0, 12)


0.125*1x1xsigma1xsigma1 + 0.125*1x1xsigma2xsigma2 + 0.125*1xsigma3xsigma1xsigma1 + 0.125*1xsigma3xsigma2xsigma2 + 0.125*sigma1x1xsigma1x1 + 0.125*sigma1x1xsigma1xsigma3 + 0.5*sigma1xsigma1x1x1 + 0.125*sigma1xsigma3xsigma1x1 + 0.125*sigma1xsigma3xsigma1xsigma3 + 0.125*sigma2x1xsigma2x1 + 0.125*sigma2x1xsigma2xsigma3 + 0.5*sigma2xsigma2x1x1 + 0.125*sigma2xsigma3xsigma2x1 + 0.125*sigma2xsigma3xsigma2xsigma3 + 0.125*sigma3x1xsigma1xsigma1 + 0.125*sigma3x1xsigma2xsigma2 + 0.125*sigma3xsigma3xsigma1xsigma1 + 0.125*sigma3xsigma3xsigma2xsigma2

In [18]:
all_states(3)

['000', '001', '010', '011', '100', '101', '110', '111']

In [19]:
T=np.ones((2,2))
T[0,0]=0
T[1,1]=0
display(T)

print_info(['01','10'],T)
print_info2(['01','10'],T)

array([[0., 1.],
       [1., 0.]])

Hamming distance= (2, 0.2)


'H='

0.5*sigma1xsigma1 + 0.5*sigma2xsigma2

#sqg, #cnots= (0, 4)
overlap with bitwise negated stringlist = ['01', '10']
minus = []
g(x)= 2*x0*x1 - x0 - x1 + 1
is zero for the following bitstrings:
0 1
1 0
m,2**n 2 4
minus = []
add minus = ['11', '00']


'H='

1.0*sigma1xsigma1

#sqg, #cnots= (0, 2)


In [20]:
T=np.ones((2,2))-np.identity(2)
display(T)

print_info(['01','10'],T)

array([[0., 1.],
       [1., 0.]])

Hamming distance= (2, 0.2)


'H='

0.5*sigma1xsigma1 + 0.5*sigma2xsigma2

#sqg, #cnots= (0, 4)
overlap with bitwise negated stringlist = ['01', '10']
minus = []
g(x)= 2*x0*x1 - x0 - x1 + 1
is zero for the following bitstrings:
0 1
1 0


In [21]:
T=np.ones((3,3))-2*np.identity(3)
display(T)

print_info(['100','010','001'],T)

T=np.ones((3,3))-np.identity(3)
display(T)

print_info(['100','010','001'],T)

T=np.ones((3,3))-np.identity(3)
T[0,2]=0
T[2,0]=0
display(T)

print_info(['100','010','001'],T)

array([[-1.,  1.,  1.],
       [ 1., -1.,  1.],
       [ 1.,  1., -1.]])

Hamming distance= (8, 4.4)


'H='

-0.375*1x1x1 - 0.125*1x1xsigma3 + 0.25*1xsigma1xsigma1 + 0.25*1xsigma2xsigma2 - 0.125*1xsigma3x1 + 0.125*1xsigma3xsigma3 + 0.25*sigma1x1xsigma1 + 0.25*sigma1xsigma1x1 + 0.25*sigma1xsigma1xsigma3 + 0.25*sigma1xsigma3xsigma1 + 0.25*sigma2x1xsigma2 + 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3 + 0.25*sigma2xsigma3xsigma2 - 0.125*sigma3x1x1 + 0.125*sigma3x1xsigma3 + 0.25*sigma3xsigma1xsigma1 + 0.25*sigma3xsigma2xsigma2 + 0.125*sigma3xsigma3x1 + 0.375*sigma3xsigma3xsigma3

#sqg, #cnots= (3, 46)


'H+H_neg='

-0.75*1x1x1 + 0.5*1xsigma1xsigma1 + 0.5*1xsigma2xsigma2 + 0.25*1xsigma3xsigma3 + 0.5*sigma1x1xsigma1 + 0.5*sigma1xsigma1x1 + 0.5*sigma2x1xsigma2 + 0.5*sigma2xsigma2x1 + 0.25*sigma3x1xsigma3 + 0.25*sigma3xsigma3x1

#sqg, #cnots= (0, 18)


'H+H_minus='

-0.75*1x1x1 + 0.5*1xsigma1xsigma1 + 0.5*1xsigma2xsigma2 + 0.25*1xsigma3xsigma3 + 0.5*sigma1x1xsigma1 + 0.5*sigma1xsigma1x1 + 0.5*sigma2x1xsigma2 + 0.5*sigma2xsigma2x1 + 0.25*sigma3x1xsigma3 + 0.25*sigma3xsigma3x1

#sqg, #cnots= (0, 18)
g(x)= -2*x0*x1*x2 + 4*x0*x1 + 4*x0*x2 - x0 + 4*x1*x2 - x1 - x2 + 1
is zero for the following bitstrings:
0 0 1
0 1 0
1 0 0


array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

Hamming distance= (8, 4.4)


'H='

0.25*1xsigma1xsigma1 + 0.25*1xsigma2xsigma2 + 0.25*sigma1x1xsigma1 + 0.25*sigma1xsigma1x1 + 0.25*sigma1xsigma1xsigma3 + 0.25*sigma1xsigma3xsigma1 + 0.25*sigma2x1xsigma2 + 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3 + 0.25*sigma2xsigma3xsigma2 + 0.25*sigma3xsigma1xsigma1 + 0.25*sigma3xsigma2xsigma2

#sqg, #cnots= (0, 36)


'H+H_neg='

0.5*1xsigma1xsigma1 + 0.5*1xsigma2xsigma2 + 0.5*sigma1x1xsigma1 + 0.5*sigma1xsigma1x1 + 0.5*sigma2x1xsigma2 + 0.5*sigma2xsigma2x1

#sqg, #cnots= (0, 12)


'H+H_minus='

0.5*1xsigma1xsigma1 + 0.5*1xsigma2xsigma2 + 0.5*sigma1x1xsigma1 + 0.5*sigma1xsigma1x1 + 0.5*sigma2x1xsigma2 + 0.5*sigma2xsigma2x1

#sqg, #cnots= (0, 12)
g(x)= -2*x0*x1*x2 + 4*x0*x1 + 4*x0*x2 - x0 + 4*x1*x2 - x1 - x2 + 1
is zero for the following bitstrings:
0 0 1
0 1 0
1 0 0


array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

Hamming distance= (6, 4.2)


'H='

0.25*1xsigma1xsigma1 + 0.25*1xsigma2xsigma2 + 0.25*sigma1xsigma1x1 + 0.25*sigma1xsigma1xsigma3 + 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3 + 0.25*sigma3xsigma1xsigma1 + 0.25*sigma3xsigma2xsigma2

#sqg, #cnots= (0, 24)


'H+H_neg='

0.5*1xsigma1xsigma1 + 0.5*1xsigma2xsigma2 + 0.5*sigma1xsigma1x1 + 0.5*sigma2xsigma2x1

#sqg, #cnots= (0, 8)


'H+H_minus='

0.5*1xsigma1xsigma1 + 0.5*1xsigma2xsigma2 + 0.5*sigma1xsigma1x1 + 0.5*sigma2xsigma2x1

#sqg, #cnots= (0, 8)
g(x)= -2*x0*x1*x2 + 4*x0*x1 + 4*x0*x2 - x0 + 4*x1*x2 - x1 - x2 + 1
is zero for the following bitstrings:
0 0 1
0 1 0
1 0 0


In [22]:
T=np.ones((3,3))-np.identity(3)
T[0,2]=0
T[2,0]=0
display(T)

print_info(['100','010','011'],T)
print_info2(['100','010','011'],T)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

Hamming distance= (6, 4.2)


'H='

0.25*1x1xsigma1 - 0.25*1xsigma3xsigma1 + 0.25*sigma1xsigma1x1 + 0.25*sigma1xsigma1xsigma3 + 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3 + 0.25*sigma3x1xsigma1 - 0.25*sigma3xsigma3xsigma1

#sqg, #cnots= (1, 20)
overlap with bitwise negated stringlist = ['100', '011']
minus = ['101']
g(x)= -2*x0*x1*x2 + 4*x0*x1 + 4*x0*x2 - 2*x0 - 2*x1*x2 - 2*x1 + 2*x2 + 2
is zero for the following bitstrings:
0 1 0
0 1 1
1 0 0
m,2**n 3 8
minus = ['101']
minus = ['101']
add minus = ['001', '111', '110']


'H='

0.5*1x1xsigma1 - 0.5*1xsigma3xsigma1 + 0.5*sigma1xsigma1x1 + 0.5*sigma2xsigma2xsigma3

#sqg, #cnots= (1, 8)


In [23]:
# for i in range(3):
#     for j in range(i+1):
#         T=np.zeros((3,3))
#         T[i,j]=1
#         T[j,i]=1
#         display(T)
# #         print_info(['100','010','001'],T,disp_d=False,disp_g=False,disp_neg=False,disp_H=False)
#         print_info2(['100','010','001'],T)

In [24]:
#     T=np.zeros((2,2))
#     str_lst=['0110','1011']
#     T[0,1]=1
#     T[1,0]=1
#     display(T,str_lst)
#     print_info(str_lst,T)

In [25]:
    T=np.zeros((2,2))
    T[0,1]=1
    T[1,0]=1
    
    str_lst=['11', '00']
    display(T,str_lst)
    print_info(str_lst,T)
    
    str_lst=['10', '01']
    display(T,str_lst)
    print_info(str_lst,T)

array([[0., 1.],
       [1., 0.]])

['11', '00']

Hamming distance= (2, 0.2)


'H='

0.5*sigma1xsigma1 - 0.5*sigma2xsigma2

#sqg, #cnots= (0, 4)
overlap with bitwise negated stringlist = ['11', '00']
minus = []
g(x)= -2*x0*x1 + x0 + x1
is zero for the following bitstrings:
0 0
1 1


array([[0., 1.],
       [1., 0.]])

['10', '01']

Hamming distance= (2, 0.2)


'H='

0.5*sigma1xsigma1 + 0.5*sigma2xsigma2

#sqg, #cnots= (0, 4)
overlap with bitwise negated stringlist = ['10', '01']
minus = []
g(x)= 2*x0*x1 - x0 - x1 + 1
is zero for the following bitstrings:
0 1
1 0


In [6]:
for n in range(2,8):
    print("----------------------")
    print("")
    T=np.zeros((2,2))
    T[0,1]=1
    T[1,0]=1
    str_lst=[]
    str_tmp='01'
    for j in range(n-2):
        str_tmp+="0"
    str_lst.append(str_tmp)
    str_tmp='10'
    for j in range(n-2):
        str_tmp+="0"
    str_lst.append(str_tmp)
    display(T,str_lst)

    H=get_H(str_lst,T)
#     display(H)
    H=simplifyH(H)
    num_Cnot(H)

----------------------



array([[0., 1.],
       [1., 0.]])

['01', '10']

----------------------



array([[0., 1.],
       [1., 0.]])

['010', '100']

----------------------



array([[0., 1.],
       [1., 0.]])

['0100', '1000']

----------------------



array([[0., 1.],
       [1., 0.]])

['01000', '10000']

----------------------



array([[0., 1.],
       [1., 0.]])

['010000', '100000']

----------------------



array([[0., 1.],
       [1., 0.]])

['0100000', '1000000']

In [27]:
for n in [2,3,4,5,6]:
    print("----------------------")
    print("")
    T=np.zeros((n,n))
    str_lst=[]
#     T[0,1]=1
#     T[1,0]=1
    for i in range(n-1):
        T[i,i+1]=1
        T[i+1,i]=1
    for i in range(n):
        str_tmp=''
        for j in range(n):
            if i==j:
                str_tmp+="1"
            else:
                str_tmp+="0"
        str_lst.append(str_tmp)
    display(T,str_lst)

    print_info2(str_lst,T)

----------------------



array([[0., 1.],
       [1., 0.]])

['10', '01']

m,2**n 2 4
minus = []
add minus = ['00', '11']


'H='

1.0*sigma1xsigma1

#sqg, #cnots= (0, 2)
----------------------



array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

['100', '010', '001']

m,2**n 3 8
add minus = ['011', '101', '110']


'H='

0.5*1xsigma1xsigma1 + 0.5*1xsigma2xsigma2 + 0.5*sigma1xsigma1x1 + 0.5*sigma2xsigma2x1

#sqg, #cnots= (0, 8)
----------------------



array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.]])

['1000', '0100', '0010', '0001']

m,2**n 4 16
add minus = ['0111', '1011', '1101', '1110']


'H='

0.25*1x1xsigma1xsigma1 + 0.25*1x1xsigma2xsigma2 + 0.25*1xsigma1xsigma1x1 + 0.25*1xsigma2xsigma2x1 + 0.25*sigma1xsigma1x1x1 + 0.25*sigma1xsigma1xsigma3xsigma3 + 0.25*sigma2xsigma2x1x1 + 0.25*sigma2xsigma2xsigma3xsigma3 + 0.25*sigma3xsigma1xsigma1xsigma3 + 0.25*sigma3xsigma2xsigma2xsigma3 + 0.25*sigma3xsigma3xsigma1xsigma1 + 0.25*sigma3xsigma3xsigma2xsigma2

#sqg, #cnots= (0, 48)
----------------------



array([[0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.]])

['10000', '01000', '00100', '00010', '00001']

m,2**n 5 32
add minus = ['01111', '10111', '11011', '11101', '11110']


'H='

0.125*1x1x1xsigma1xsigma1 + 0.125*1x1x1xsigma2xsigma2 + 0.125*1x1xsigma1xsigma1x1 + 0.125*1x1xsigma2xsigma2x1 + 0.125*1xsigma1xsigma1x1x1 + 0.125*1xsigma1xsigma1xsigma3xsigma3 + 0.125*1xsigma2xsigma2x1x1 + 0.125*1xsigma2xsigma2xsigma3xsigma3 + 0.125*1xsigma3xsigma1xsigma1xsigma3 + 0.125*1xsigma3xsigma2xsigma2xsigma3 + 0.125*1xsigma3xsigma3xsigma1xsigma1 + 0.125*1xsigma3xsigma3xsigma2xsigma2 + 0.125*sigma1xsigma1x1x1x1 + 0.125*sigma1xsigma1x1xsigma3xsigma3 + 0.125*sigma1xsigma1xsigma3x1xsigma3 + 0.125*sigma1xsigma1xsigma3xsigma3x1 + 0.125*sigma2xsigma2x1x1x1 + 0.125*sigma2xsigma2x1xsigma3xsigma3 + 0.125*sigma2xsigma2xsigma3x1xsigma3 + 0.125*sigma2xsigma2xsigma3xsigma3x1 + 0.125*sigma3x1xsigma1xsigma1xsigma3 + 0.125*sigma3x1xsigma2xsigma2xsigma3 + 0.125*sigma3x1xsigma3xsigma1xsigma1 + 0.125*sigma3x1xsigma3xsigma2xsigma2 + 0.125*sigma3xsigma1xsigma1x1xsigma3 + 0.125*sigma3xsigma1xsigma1xsigma3x1 + 0.125*sigma3xsigma2xsigma2x1xsigma3 + 0.125*sigma3xsigma2xsigma2xsigma3x1 + 0.125*sigma3xsig

#sqg, #cnots= (0, 160)
----------------------



array([[0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0.]])

['100000', '010000', '001000', '000100', '000010', '000001']

m,2**n 6 64
add minus = ['011111', '101111', '110111', '111011', '111101', '111110']


'H='

0.0625*1x1x1x1xsigma1xsigma1 + 0.0625*1x1x1x1xsigma2xsigma2 + 0.0625*1x1x1xsigma1xsigma1x1 + 0.0625*1x1x1xsigma2xsigma2x1 + 0.0625*1x1xsigma1xsigma1x1x1 + 0.0625*1x1xsigma1xsigma1xsigma3xsigma3 + 0.0625*1x1xsigma2xsigma2x1x1 + 0.0625*1x1xsigma2xsigma2xsigma3xsigma3 + 0.0625*1x1xsigma3xsigma1xsigma1xsigma3 + 0.0625*1x1xsigma3xsigma2xsigma2xsigma3 + 0.0625*1x1xsigma3xsigma3xsigma1xsigma1 + 0.0625*1x1xsigma3xsigma3xsigma2xsigma2 + 0.0625*1xsigma1xsigma1x1x1x1 + 0.0625*1xsigma1xsigma1x1xsigma3xsigma3 + 0.0625*1xsigma1xsigma1xsigma3x1xsigma3 + 0.0625*1xsigma1xsigma1xsigma3xsigma3x1 + 0.0625*1xsigma2xsigma2x1x1x1 + 0.0625*1xsigma2xsigma2x1xsigma3xsigma3 + 0.0625*1xsigma2xsigma2xsigma3x1xsigma3 + 0.0625*1xsigma2xsigma2xsigma3xsigma3x1 + 0.0625*1xsigma3x1xsigma1xsigma1xsigma3 + 0.0625*1xsigma3x1xsigma2xsigma2xsigma3 + 0.0625*1xsigma3x1xsigma3xsigma1xsigma1 + 0.0625*1xsigma3x1xsigma3xsigma2xsigma2 + 0.0625*1xsigma3xsigma1xsigma1x1xsigma3 + 0.0625*1xsigma3xsigma1xsigma1xsigma3x1 + 0.0625*1xsigma

#sqg, #cnots= (0, 480)


In [28]:
T=np.ones((2,2))-np.identity(2)
# T[2,0]=0
# T[0,2]=0
display(T)

print_info(['100','010'],T)

array([[0., 1.],
       [1., 0.]])

Hamming distance= (2, 0.2)


'H='

0.25*sigma1xsigma1x1 + 0.25*sigma1xsigma1xsigma3 + 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3

#sqg, #cnots= (0, 12)


'H+H_neg='

0.5*sigma1xsigma1x1 + 0.5*sigma2xsigma2x1

#sqg, #cnots= (0, 4)


'H+H_minus='

0.5*sigma1xsigma1x1 + 0.5*sigma2xsigma2x1

#sqg, #cnots= (0, 4)
g(x)= 2*x0*x1 - x0 - x1 + 3*x2 + 1
is zero for the following bitstrings:
0 1 0
1 0 0


In [29]:
T=np.ones((2,2))-np.identity(2)
display(T)
print_info(['001','110'],T)

array([[0., 1.],
       [1., 0.]])

Hamming distance= (2, 0.2)


'H='

0.25*sigma1xsigma1xsigma1 + 0.25*sigma1xsigma2xsigma2 + 0.25*sigma2xsigma1xsigma2 - 0.25*sigma2xsigma2xsigma1

#sqg, #cnots= (0, 16)
overlap with bitwise negated stringlist = ['001', '110']
minus = []
g(x)= -2*x0*x1 + 2*x0*x2 + 2*x1*x2 - 2*x2 + 2
is zero for the following bitstrings:
0 0 1
1 1 0


In [30]:
T=np.ones((3,3))-np.identity(3)
T[2,0]=0
T[0,2]=0
display(T)

print_info(['001','101','110'],T)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

Hamming distance= (6, 4.2)


'H='

0.25*1xsigma1xsigma1 + 0.25*1xsigma2xsigma2 + 0.25*sigma1x1x1 - 0.25*sigma1x1xsigma3 + 0.25*sigma1xsigma3x1 - 0.25*sigma1xsigma3xsigma3 - 0.25*sigma3xsigma1xsigma1 - 0.25*sigma3xsigma2xsigma2

#sqg, #cnots= (1, 20)
overlap with bitwise negated stringlist = ['001', '110']
minus = ['010']
g(x)= 2*x0*x1*x2 - 4*x0*x1 + 2*x0*x2 - 2*x0 + 2*x1*x2 + 2*x1 - 4*x2 + 4
is zero for the following bitstrings:
0 0 1
1 0 1
1 1 0


In [31]:
T=np.ones((3,3))-np.identity(3)
T[2,0]=0
T[0,2]=0
display(T)

print_info(['001','111','101'],T)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

Hamming distance= (6, 4.2)


'H='

0.25*1xsigma1x1 - 0.25*1xsigma1xsigma3 + 0.25*sigma1xsigma1x1 - 0.25*sigma1xsigma1xsigma3 - 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3 - 0.25*sigma3xsigma1x1 + 0.25*sigma3xsigma1xsigma3

#sqg, #cnots= (1, 20)


'H+H_neg='

0.5*1xsigma1x1 + 0.5*sigma1xsigma1x1 - 0.5*sigma2xsigma2x1 + 0.5*sigma3xsigma1xsigma3

#sqg, #cnots= (1, 8)


'H+H_minus='

0.5*1xsigma1x1 + 0.5*sigma1xsigma1x1 - 0.5*sigma2xsigma2x1 + 0.5*sigma3xsigma1xsigma3

#sqg, #cnots= (1, 8)
g(x)= 2*x0*x1*x2 - 4*x0*x1 + 2*x0*x2 - 2*x0 - 4*x1*x2 + 6*x1 - 6*x2 + 6
is zero for the following bitstrings:
0 0 1
1 0 1
1 1 1


In [32]:
T=np.ones((2,2))-np.identity(2)
display(T)

print_info(['000','111'],T)

array([[0., 1.],
       [1., 0.]])

Hamming distance= (2, 0.2)


'H='

0.25*sigma1xsigma1xsigma1 - 0.25*sigma1xsigma2xsigma2 - 0.25*sigma2xsigma1xsigma2 - 0.25*sigma2xsigma2xsigma1

#sqg, #cnots= (0, 16)
overlap with bitwise negated stringlist = ['000', '111']
minus = []
g(x)= -2*x0*x1 - 2*x0*x2 + 2*x0 - 2*x1*x2 + 2*x1 + 2*x2
is zero for the following bitstrings:
0 0 0
1 1 1


In [33]:
n=2
T=np.zeros((2**n,2**n))
for i in range(2**n-1):
    T[i,i+1]=1
    T[i+1,i]=1
display(T)

print_info(['100','010','001','011'],T)

array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.]])

Hamming distance= (8, 4.3999999999999995)


'H='

0.25*1xsigma1x1 + 0.25*1xsigma1xsigma1 - 0.25*1xsigma1xsigma3 + 0.25*1xsigma2xsigma2 + 0.25*sigma1xsigma1x1 + 0.25*sigma1xsigma1xsigma3 + 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3 + 0.25*sigma3xsigma1x1 + 0.25*sigma3xsigma1xsigma1 - 0.25*sigma3xsigma1xsigma3 + 0.25*sigma3xsigma2xsigma2

#sqg, #cnots= (1, 32)
overlap with bitwise negated stringlist = ['100', '011']


'H+H_minus='

0.25*1xsigma1x1 + 0.5*1xsigma1xsigma1 - 0.25*1xsigma1xsigma3 + 0.5*1xsigma2xsigma2 + 0.25*sigma1xsigma1x1 + 0.25*sigma1xsigma1xsigma3 + 0.25*sigma2xsigma2x1 + 0.25*sigma2xsigma2xsigma3 + 0.25*sigma3xsigma1x1 - 0.25*sigma3xsigma1xsigma3

#sqg, #cnots= (1, 24)
g(x)= -6*x0*x1*x2 + 8*x0*x1 + 8*x0*x2 - 2*x0 + 2*x1*x2 - 2*x1 - 2*x2 + 2
is zero for the following bitstrings:
0 0 1
0 1 0
0 1 1
1 0 0
